### ISSUE TITLE
import segment

### ISSUE THREAD

**Issue by Guigo95** [pixano/pixano-inference#15] opened 2024-03-01 13:16 UTC
Hello,

On the latest version, the command :

from pixano_inference import segment_anything

does not work for me.

When I look in conda's env in site packages, I can't find segment_anything, whereas it appears in the previous version.

Could you take a look?

Thanks !

**Comment by cpvannier** [comment] 2024-03-01 13:53
Hi,

The `segment_anything` module has been renamed to GitHub as we will soon add more models from GitHub repositories alongside SAM.

So you can now call SAM with `from pixano_inference import github` and then `github.SAM()`.

Let me know if you have any other questions!

**Comment by Guigo95** [comment] 2024-03-01 14:13
Yes, that's what I did! I also had to comment
from .mobile_sam import MobileSAM
in the __init__ file because of an import error.

I now have a problem with onnxruntime:

Traceback (most recent call last):
  File "C:\Users\gg268966\AppData\Local\anaconda3\envs\pixano-beta3\lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-b0f7fe366fc9>", line 1, in <module>
    from pixano_inference import github
  File "C:\Users\gg268966\AppData\Local\JetBrains\PyCharm Community Edition 2023.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\gg268966\AppData\Local\anaconda3\envs\pixano-beta3\lib\site-packages\pixano_inference\github\__init__.py", line 15, in <module>
    from .sam import SAM
  File "C:\Users\gg268966\AppData\Local\JetBrains\PyCharm Community Edition 2023.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\gg268966\AppData\Local\anaconda3\envs\pixano-beta3\lib\site-packages\pixano_inference\github\sam.py", line 23, in <module>
    from onnxruntime.quantization import QuantType
  File "C:\Users\gg268966\AppData\Local\JetBrains\PyCharm Community Edition 2023.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\gg268966\AppData\Roaming\Python\Python310\site-packages\onnxruntime\quantization\__init__.py", line 1, in <module>
    from .calibrate import (  # noqa: F401
  File "C:\Users\gg268966\AppData\Local\JetBrains\PyCharm Community Edition 2023.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\gg268966\AppData\Roaming\Python\Python310\site-packages\onnxruntime\quantization\calibrate.py", line 22, in <module>
    from .quant_utils import apply_plot, load_model_with_shape_infer, smooth_distribution
  File "C:\Users\gg268966\AppData\Local\JetBrains\PyCharm Community Edition 2023.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\gg268966\AppData\Roaming\Python\Python310\site-packages\onnxruntime\quantization\quant_utils.py", line 123, in <module>
    onnx_proto.TensorProto.FLOAT8E4M3FN: float8e4m3fn,
AttributeError: FLOAT8E4M3FN

I already had this error with a previous version of pixano-inference, but not all, I don't remember which one ...
Which version do you recommend?
I have 
onnx → 1.13.1
onnxruntime→1.15.1

I only install pixano-inference on a fresh conda environnement

**Comment by cpvannier** [comment] 2024-03-04 09:01
Hi,

Regarding the import error with MobileSAM, we are aware of the issue and PR #6 will fix this (0dc083df269687d4c4ae23c08758492c5a55fe68). In the meantime you can indeed comment the import.

For the ONNX `AttributeError: FLOAT8E4M3FN` issue, we are aware of this issue as well. Pixano 0.5.0 and Pixano Inference 0.3.0 are supposed to fix the issue by specifiying the correct version of onnxruntime. It looks like you already have the correct versions, but we already encountered users in the same situation, and in their case creating a new conda environment different for this new version of Pixano Inference seemed to fix the issue.

**Comment by Guigo95** [comment] 2024-03-04 10:36
Hi,

I already tried to create a fresh evironnement, but it's not helping ...  I did it again this morning with the same result.

Any ideas?

**Comment by cpvannier** [comment] 2024-03-04 11:55
I am thinking that maybe the fresh environnement isn't helping because your notebook is not calling the correct version of `onnxruntime`.

Looking at your logs above, when you have a call to `pixano-inference`, the path looks like this:
```
AppData\Local\anaconda3\envs\pixano-beta3\lib\site-packages\pixano_inference
```
So this is the version of `pixano-inference` installed in the `pixano-beta3` environment.

But for the `onnxruntime` error, the path is:
```
AppData\Roaming\Python\Python310\site-packages\onnxruntime
```
So the version of `onnxruntime` called by your notebook is from your default Python environment, not from your conda environment.

I would suggest making sure that your notebook and your PyCharm workspace are configured with the correct conda environment, and I would uninstall `onnx` and `onnxruntime` from the default Python environment, to make sure only the versions in the conda environment can be used.

**Comment by Guigo95** [comment] 2024-03-05 09:06
Hi, that was it, thanks !

I have one last (I hope ...) problem, when I launch the app from the notebook, nothing happens. I get a blank page if a use the link http://127.0.0.1:8000. I tried to restart google, but same result
The log:

INFO:     Started server process [25104]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:58235 - "GET / HTTP/1.1" 200 OK
have you ever encountered this problem ?

**Comment by cpvannier** [comment] 2024-03-05 09:13
That's weird, I just checked and I am not having that issue.

Does the `app.display()` cell below shows you a blank page as well?

**Comment by Guigo95** [comment] 2024-03-05 09:26
I get: "127.0.0.1 n'autorise pas la connexion" in the notebook. it's working for cecile too

**Comment by Guigo95** [comment] 2024-03-05 11:59
I tried app  App(root_directory,port=9090) with no success

**Comment by Guigo95** [comment] 2024-03-05 13:41
I get a different port, but same issue:
![Capture](https://github.com/pixano/pixano-inference/assets/41192748/847d4b04-65d8-4125-a224-9dc28ee96ce5)

**Comment by cpvannier** [comment] 2024-03-06 09:35
No errors from Pixano, so I'm not sure what could be causing this.

Is the page completely blank or do you see the Pixano header but just no datasets?

**Comment by Guigo95** [comment] 2024-03-06 13:36
It's working well on another computer, using my session and the same code. Probably a problem with my computer. I called the 111, I'll update you if there are any new developments

**Comment by cpvannier** [comment] 2024-03-07 12:28
Alright.

I am closing this since the problem is different from the initial topic of the issue, and relates with using Pixano and not Pixano Inference.

It looks like an issue with your device indeed. You can keep me updated here if it gets fixed, and if it turns out that something in Pixano is causing this, please create a new issue on the Pixano repository.

**Closed by cpvannier** 2024-03-07 12:28 UTC
